name: build

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install build dependencies
      run: sudo apt-get -y install build-essential libnfnetlink-dev libnetfilter-queue-dev libsystemd-dev

    - name: Build
      run: make out/glass-trans
    
    - name: Config iptables
      run: sudo iptables -A INPUT -p tcp --dport 61000:63000  -j NFQUEUE --queue-num 6
    
    - name: Init directory structure
      run: sudo mkdir -p /var/run/glass/

    - name: Test glass-trans
      run: cd test && ./test.sh
