name: Build

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install build dependencies
      run: sudo apt-get -y install build-essential libnfnetlink-dev libnetfilter-queue-dev

    - name: Build
      run: make out/glass
